-- Display all the grade 4, 5 Analyst and Manager.

SELECT *
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN LOSAL AND HISAL AND S.GRADE IN (4, 5) AND
E.EMPNO IN (SELECT E.EMPNO
FROM EMP E
WHERE E.JOB IN('ANALYST', 'MANAGER'));
