-- List the most senior emps working under the King and grade is more than 3.

SELECT *
FROM EMP
WHERE HIREDATE IN (SELECT MIN(HIREDATE)
FROM EMP 
WHERE EMPNO IN (SELECT EMPNO 
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE IN (4, 5))) AND MGR IN (SELECT EMPNO
FROM EMP
WHERE ENAME = 'KING');
