-- List the name, job, dname, sal grade dept wise.

SELECT E.ENAME, E.JOB, D.DNAME, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO AND E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY D.DEPTNO;
